export const frecuenciaEquivalenteMap: { [key: string]: string } = {
  Diario: 'LV',
  Interdiario: 'LMV',
  'Interdiario L-M': 'LM',
  'Interdiario M-V': 'MV',
  'Interdiario L-M-V': 'LMV',
  Dominical: 'D',
  Sabatino: 'S',
  'Sabatino Dominical': 'SD',
  'Interdiario M-J': 'MJ',
  'Interdiario M-J-S': 'MJS',
  Lunes: 'L',
  Jueves: 'J',
  Martes: 'M',
  Miercoles: 'M',
  Viernes: 'V',
};
